from PyQt5 import QtCore, QtGui, QtWidgets


class AbrirApneas(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(2000, 1600))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 1600))
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 1800))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setMinimumSize(QtCore.QSize(0, 90))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.label_ID = QtWidgets.QLabel(self.frame)
        self.label_ID.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_ID.setFont(font)
        self.label_ID.setStyleSheet("color: rgb(156, 156, 156);")
        self.label_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID.setWordWrap(True)
        self.label_ID.setObjectName("label_ID")
        self.horizontalLayout_3.addWidget(self.label_ID)
        
        self.label_idescribir = QtWidgets.QLabel(self.frame)
        self.label_idescribir.setMinimumSize(QtCore.QSize(400, 0))
        self.label_idescribir.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_idescribir.setFont(font)
        self.label_idescribir.setStyleSheet("color: rgb(156, 156, 156);")
        self.label_idescribir.setAlignment(QtCore.Qt.AlignCenter)
        self.label_idescribir.setObjectName("label_idescribir")
        self.horizontalLayout_3.addWidget(self.label_idescribir)
        spacerItem = QtWidgets.QSpacerItem(900, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        
        self.label_NombreApellido = QtWidgets.QLabel(self.frame)
        self.label_NombreApellido.setMinimumSize(QtCore.QSize(400, 0))
        self.label_NombreApellido.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_NombreApellido.setFont(font)
        self.label_NombreApellido.setStyleSheet("color: rgb(156, 156, 156);")
        self.label_NombreApellido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NombreApellido.setWordWrap(True)
        self.label_NombreApellido.setObjectName("label_NombreApellido")
        self.horizontalLayout_3.addWidget(self.label_NombreApellido)
        
        self.label_nombreap = QtWidgets.QLabel(self.frame)
        self.label_nombreap.setMinimumSize(QtCore.QSize(400, 0))
        self.label_nombreap.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_nombreap.setFont(font)
        self.label_nombreap.setStyleSheet("color: rgb(156, 156, 156);")
        self.label_nombreap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nombreap.setWordWrap(True)
        self.label_nombreap.setObjectName("label_nombreap")
        self.horizontalLayout_3.addWidget(self.label_nombreap)
        
        # self.boton_otropac = QtWidgets.QPushButton(self.frame)
        # self.boton_otropac.setMinimumSize(QtCore.QSize(255, 70))
        # self.boton_otropac.setMaximumSize(QtCore.QSize(255, 16777215))
        # font = QtGui.QFont()
        # font.setPointSize(8)
        # font.setBold(True)
        # font.setWeight(75)
        # self.boton_otropac.setFont(font)
        # self.boton_otropac.setStyleSheet("background-color: rgb(145, 145, 145);")
        # self.boton_otropac.setObjectName("boton_otropac")
        # self.horizontalLayout_3.addWidget(self.boton_otropac)
        # spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.horizontalLayout_3.addItem(spacerItem1)
        
        self.boton_atras = QtWidgets.QPushButton(self.frame)
        self.boton_atras.setMinimumSize(QtCore.QSize(200, 70))
        self.boton_atras.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.boton_atras.setFont(font)
        self.boton_atras.setStyleSheet("background-color: rgb(145, 145, 145);")
        self.boton_atras.setObjectName("boton_atras")
        self.horizontalLayout_3.addWidget(self.boton_atras)
        self.verticalLayout.addWidget(self.frame)
        
        self.frame_titulo = QtWidgets.QFrame(self.centralwidget)
        self.frame_titulo.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_titulo.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_titulo.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titulo.setObjectName("frame_titulo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_titulo)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.label_titulo = QtWidgets.QLabel(self.frame_titulo)
        self.label_titulo.setMinimumSize(QtCore.QSize(250, 40))
        self.label_titulo.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.horizontalLayout_2.addWidget(self.label_titulo)
        
        self.label_Napenas = QtWidgets.QLabel(self.frame_titulo)
        self.label_Napenas.setMinimumSize(QtCore.QSize(150, 0))
        self.label_Napenas.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_Napenas.setFont(font)
        self.label_Napenas.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Napenas.setWordWrap(True)
        self.label_Napenas.setObjectName("label_Napenas")
        self.horizontalLayout_2.addWidget(self.label_Napenas)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        
        self.label_seleccione = QtWidgets.QLabel(self.frame_titulo)
        self.label_seleccione.setMinimumSize(QtCore.QSize(600, 59))
        self.label_seleccione.setMaximumSize(QtCore.QSize(600, 16777215))
        self.label_seleccione.setStyleSheet("color: rgb(156, 156, 156);")
        self.label_seleccione.setAlignment(QtCore.Qt.AlignCenter)
        self.label_seleccione.setWordWrap(True)
        self.label_seleccione.setObjectName("label_seleccione")
        self.horizontalLayout_2.addWidget(self.label_seleccione)
        
        self.comboBox = QtWidgets.QComboBox(self.frame_titulo)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 60))
        self.comboBox.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.comboBox.setObjectName("comboBox")

        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame_titulo)
        
        self.frame_apneas = QtWidgets.QFrame(self.centralwidget)
        self.frame_apneas.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_apneas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_apneas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_apneas.setObjectName("frame_apneas")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_apneas)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.frame_apneas = QtWidgets.QFrame(self.centralwidget)
        self.frame_apneas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_apneas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_apneas.setObjectName("frame_apneas")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_apneas)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.frame_uno = QtWidgets.QFrame(self.frame_apneas)
        self.frame_uno.setMinimumSize(QtCore.QSize(530, 0))
        self.frame_uno.setMaximumSize(QtCore.QSize(620, 16777215))
        self.frame_uno.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_uno.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_uno.setObjectName("frame_uno")
        
        self.gridLayout = QtWidgets.QGridLayout(self.frame_uno)
        self.gridLayout.setContentsMargins(0, 0, 4, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        
       
        self.label_PR = QtWidgets.QLabel(self.frame_uno)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_PR.setFont(font)
        self.label_PR.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_PR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PR.setWordWrap(True)
        self.label_PR.setObjectName("label_PR")
        self.gridLayout.addWidget(self.label_PR, 1, 0, 1, 1)
        
        self.lineEdit_PR = QtWidgets.QLabel(self.frame_uno)
        self.lineEdit_PR.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_PR.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_PR.setObjectName("lineEdit_PR")
        self.gridLayout.addWidget(self.lineEdit_PR, 1, 2, 1, 1)
        
        self.label_inicio = QtWidgets.QLabel(self.frame_uno)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_inicio.setFont(font)
        self.label_inicio.setMinimumSize(QtCore.QSize(250, 50))
        self.label_inicio.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_inicio.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inicio.setObjectName("label_inicio")
        self.gridLayout.addWidget(self.label_inicio, 0, 0, 1, 1)
        
        self.label_3 = QtWidgets.QLabel(self.frame_uno)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        
        self.lineEdit_spo2prom = QtWidgets.QLabel(self.frame_uno)
        self.lineEdit_spo2prom.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_spo2prom.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_spo2prom.setObjectName("lineEdit_spo2prom")
        self.gridLayout.addWidget(self.lineEdit_spo2prom, 3, 2, 1, 1)
        
        self.label = QtWidgets.QLabel(self.frame_uno)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        
        self.lineEdit_spo2min = QtWidgets.QLabel(self.frame_uno)
        self.lineEdit_spo2min.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_spo2min.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_spo2min.setObjectName("lineEdit_spo2min")
        self.gridLayout.addWidget(self.lineEdit_spo2min, 2, 2, 1, 1)
        
        self.lineEdit_inicio = QtWidgets.QLabel(self.frame_uno)
        self.lineEdit_inicio.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_inicio.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_inicio.setObjectName("lineEdit_inicio")
        self.gridLayout.addWidget(self.lineEdit_inicio, 0, 2, 1, 1)
        
        self.lineEdit_HRmin = QtWidgets.QLabel(self.frame_uno)
        self.lineEdit_HRmin.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_HRmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_HRmin.setObjectName("lineEdit_HRmin")
        self.gridLayout.addWidget(self.lineEdit_HRmin, 6, 2, 1, 1)
        
        self.label_4 = QtWidgets.QLabel(self.frame_uno)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        
        self.label_2 = QtWidgets.QLabel(self.frame_uno)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        
        self.label_5 = QtWidgets.QLabel(self.frame_uno)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        
        self.lineEdit_HRmax = QtWidgets.QLabel(self.frame_uno)
        self.lineEdit_HRmax.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_HRmax.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_HRmax.setObjectName("lineEdit_HRmax")
        self.gridLayout.addWidget(self.lineEdit_HRmax, 5, 2, 1, 1)
        
        self.lineEdit_HRprom = QtWidgets.QLabel(self.frame_uno)
        self.lineEdit_HRprom.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_HRprom.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_HRprom.setObjectName("lineEdit_HRprom")
        
        self.gridLayout.addWidget(self.lineEdit_HRprom, 4, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame_uno)
        
        self.frame_dos = QtWidgets.QFrame(self.frame_apneas)
        self.frame_dos.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_dos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_dos.setStyleSheet("color: rgb(0, 0, 0);")
        self.frame_dos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dos.setObjectName("frame_dos")
        
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_dos)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
       
        self.label_grafico = QtWidgets.QLabel(self.frame_dos)
        self.label_grafico.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_grafico.setObjectName("label_grafico")
        self.gridLayout_2.addWidget(self.label_grafico, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_dos)
        self.verticalLayout.addWidget(self.frame_apneas)
        
        self.frame_pdfylineedit = QtWidgets.QFrame(self.centralwidget)
        self.frame_pdfylineedit.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_pdfylineedit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pdfylineedit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pdfylineedit.setObjectName("frame_pdfylineedit")
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_pdfylineedit)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.frame_lineedit = QtWidgets.QFrame(self.frame_pdfylineedit)
        self.frame_lineedit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lineedit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lineedit.setObjectName("frame_lineedit")
        
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_lineedit)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        self.textEdit = QtWidgets.QTextEdit(self.frame_lineedit)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_lineedit)
        self.textEdit.setPlainText("Observaciones:")
        self.textEdit.setStyleSheet("color: rgb(255, 255, 255);")
        
        self.frame_pdf = QtWidgets.QFrame(self.frame_pdfylineedit)
        self.frame_pdf.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_pdf.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_pdf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pdf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pdf.setObjectName("frame_pdf")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_pdf)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.frame_botonpdf = QtWidgets.QFrame(self.frame_pdf)
        self.frame_botonpdf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botonpdf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botonpdf.setObjectName("frame_botonpdf")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_botonpdf)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        self.pushButton_PDF = QtWidgets.QPushButton(self.frame_botonpdf)
        self.pushButton_PDF.setMinimumSize(QtCore.QSize(250, 70))
        self.pushButton_PDF.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()        
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_PDF.setFont(font)
        self.pushButton_PDF.setStyleSheet("background-color: rgb(145, 145, 145);")
        self.pushButton_PDF.setObjectName("pushButton_PDF")
        self.gridLayout_4.addWidget(self.pushButton_PDF, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_botonpdf)
        
        self.frame_otroboton = QtWidgets.QFrame(self.frame_pdf)
        self.frame_otroboton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_otroboton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_otroboton.setObjectName("frame_otroboton")
        self.verticalLayout_2.addWidget(self.frame_otroboton)
        self.horizontalLayout_4.addWidget(self.frame_pdf)
        self.verticalLayout.addWidget(self.frame_pdfylineedit)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "  Historial del paciente"))
        self.label_ID.setText(_translate("MainWindow", "ID:"))
        self.label_idescribir.setText(_translate("MainWindow", ""))
        self.label_NombreApellido.setText(_translate("MainWindow", "Nombre y apellido:"))
        # self.boton_otropac.setText(_translate("MainWindow", "Nueva consulta"))
        self.label_nombreap.setText(_translate("MainWindow", ""))
        self.boton_atras.setText(_translate("MainWindow", "Atras"))
        self.label_titulo.setText(_translate("MainWindow", "Nº APNEAS:"))
        self.label_Napenas.setText(_translate("MainWindow", ""))
        self.label_seleccione.setText(_translate("MainWindow", "Seleccione la apnea que desea visualizar:"))
        self.label_inicio.setText(_translate("MainWindow", "Inicio:"))
        self.label_2.setText(_translate("MainWindow", "SpO2 mínima:"))
        self.label_3.setText(_translate("MainWindow", "SpO2 promedio:"))
        self.label_PR.setText(_translate("MainWindow", "Pausa resp.:"))
        self.label.setText(_translate("MainWindow", "HR mínimo:"))
        self.label_4.setText(_translate("MainWindow", "HR máximo:"))
        self.label_5.setText(_translate("MainWindow", "HR promedio:"))
        self.pushButton_PDF.setText(_translate("MainWindow", "Descargar PDF"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = AbrirApneas()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
