from PyQt5 import QtCore, QtGui, QtWidgets


class AbrirDatosPaciente(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1300)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 1300))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 1400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_arriba = QtWidgets.QFrame(self.centralwidget)
        self.frame_arriba.setMinimumSize(QtCore.QSize(0, 800))
        self.frame_arriba.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.frame_arriba.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_arriba.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_arriba.setObjectName("frame_arriba")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_arriba)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_titulo = QtWidgets.QFrame(self.frame_arriba)
        self.frame_titulo.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_titulo.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_titulo.setFont(font)
        self.frame_titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titulo.setObjectName("frame_titulo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_titulo)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_titulo = QtWidgets.QLabel(self.frame_titulo)
        self.label_titulo.setMinimumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setWordWrap(True)
        self.label_titulo.setObjectName("label_titulo")
        self.horizontalLayout_2.addWidget(self.label_titulo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_titulo)
        self.frame_escribir = QtWidgets.QFrame(self.frame_arriba)
        self.frame_escribir.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_escribir.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_escribir.setObjectName("frame_escribir")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_escribir)
        self.gridLayout.setObjectName("gridLayout")
        self.label_17 = QtWidgets.QLabel(self.frame_escribir)
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 7, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_escribir)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_8.setWordWrap(True)
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_escribir)
        self.label_11.setMinimumSize(QtCore.QSize(400, 0))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_escribir)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_escribir)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_escribir)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_escribir)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setMinimumSize(QtCore.QSize(500, 0))
        # self.label_4.setMaximumSize(QtCore.QSize(00, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_escribir)
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.label_15.setObjectName("label_15")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_15, 5, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_escribir)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 1, 1, 1)
        # self.label_5 = QtWidgets.QLabel(self.frame_escribir)
        # self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # font.setBold(True)
        # font.setWeight(75)
        # self.label_5.setFont(font)
        # self.label_5.setObjectName("label_5")
        # self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_escribir)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_escribir)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_escribir)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_escribir)
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_escribir)
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 8, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        # self.label_14 = QtWidgets.QLabel(self.frame_escribir)
        # self.label_14.setStyleSheet("background-color: rgb(255, 255, 255);\n""")
        # self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_14.setObjectName("label_14")
        # self.gridLayout.addWidget(self.label_14, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_escribir)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_escribir)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_escribir)
        self.verticalLayout.addWidget(self.frame_arriba)
        self.frame_botones = QtWidgets.QFrame(self.centralwidget)
        self.frame_botones.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botones.setObjectName("frame_botones")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_botones)
        self.horizontalLayout.setContentsMargins(2, 4, 2, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boton_historial = QtWidgets.QPushButton(self.frame_botones)
        self.boton_historial.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.boton_historial.setFont(font)
        self.boton_historial.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.boton_historial.setObjectName("boton_historial")
        self.horizontalLayout.addWidget(self.boton_historial)
        self.boton_atras = QtWidgets.QPushButton(self.frame_botones)
        self.boton_atras.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.boton_atras.setFont(font)
        self.boton_atras.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.boton_atras.setObjectName("boton_atras")
        self.horizontalLayout.addWidget(self.boton_atras)
        self.verticalLayout.addWidget(self.frame_botones)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "  Datos del paciente"))
        self.label_titulo.setText(_translate("MainWindow", "Datos del paciente"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Fecha de ingreso (DD.MM.AAAA):"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Peso actual [g]:"))
        self.label_3.setText(_translate("MainWindow", "Apellido:"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.label_4.setText(_translate("MainWindow", "Fecha de nacimiento (DD.MM.AAAA):"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "Médico:"))
        # self.label_5.setText(_translate("MainWindow", "Edad [días]:"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Nombre:"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        # self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "Peso al nacer [g]:"))
        self.boton_historial.setText(_translate("MainWindow", "Historial"))
        self.boton_atras.setText(_translate("MainWindow", "Atrás"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = AbrirDatosPaciente()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
