from PyQt5 import QtCore, QtGui, QtWidgets
#firebase
import firebase_admin
from firebase_admin import firestore
import json
from firebase_admin import credentials, db
from credentials_firebase import cred
db=firestore.client() #defino database

class RegistrarDatosPaciente(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1300)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 1300))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1400))
       
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.frame_arriba = QtWidgets.QFrame(self.centralwidget)
        self.frame_arriba.setMinimumSize(QtCore.QSize(0, 800))
        self.frame_arriba.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.frame_arriba.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_arriba.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_arriba.setObjectName("frame_arriba")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_arriba)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.frame_titulo = QtWidgets.QFrame(self.frame_arriba)
        self.frame_titulo.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_titulo.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_titulo.setFont(font)
        self.frame_titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titulo.setObjectName("frame_titulo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_titulo)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_titulo = QtWidgets.QLabel(self.frame_titulo)
        self.label_titulo.setMinimumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setWordWrap(True)
        self.label_titulo.setObjectName("label_titulo")
        self.horizontalLayout_2.addWidget(self.label_titulo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_titulo)
        
        self.frame_escribir = QtWidgets.QFrame(self.frame_arriba)
        self.frame_escribir.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_escribir.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_escribir.setObjectName("frame_escribir")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_escribir)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.frame_escribir)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_8.setWordWrap(True)
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_escribir)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_escribir)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)

        self.label_4 = QtWidgets.QLabel(self.frame_escribir)
        self.label_4.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_escribir)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 1, 1, 1)
        # self.label_5 = QtWidgets.QLabel(self.frame_escribir)
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # font.setBold(True)
        # font.setWeight(75)
        # self.label_5.setFont(font)
        # self.label_5.setObjectName("label_5")
        # self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_escribir)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_escribir)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.frame_escribir)
        self.lineEdit_nombre.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.gridLayout.addWidget(self.lineEdit_nombre, 1, 2, 1, 1)
        self.lineEdit_nombre.setAlignment(QtCore.Qt.AlignCenter)
        
        self.lineEdit_apellido = QtWidgets.QLineEdit(self.frame_escribir)
        self.lineEdit_apellido.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_apellido.setObjectName("lineEdit_apellido")
        self.gridLayout.addWidget(self.lineEdit_apellido, 2, 2, 1, 1)
        self.lineEdit_apellido.setAlignment(QtCore.Qt.AlignCenter)
        
        self.lineEdit_fechanac = QtWidgets.QLineEdit(self.frame_escribir)
        self.lineEdit_fechanac.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_fechanac.setObjectName("lineEdit_fechanac")
        self.gridLayout.addWidget(self.lineEdit_fechanac, 3, 2, 1, 1)
        self.lineEdit_fechanac.setAlignment(QtCore.Qt.AlignCenter)
        
        # self.lineEdit_meses = QtWidgets.QLineEdit(self.frame_escribir)
        # self.lineEdit_meses.setMinimumSize(QtCore.QSize(0, 50))
        # self.lineEdit_meses.setObjectName("lineEdit_meses")
        # self.gridLayout.addWidget(self.lineEdit_meses, 4, 2, 1, 1)
        # self.lineEdit_meses.setAlignment(QtCore.Qt.AlignCenter)
         
        self.lineEdit_pesonacer = QtWidgets.QLineEdit(self.frame_escribir)
        self.lineEdit_pesonacer.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_pesonacer.setObjectName("lineEdit_pesonacer")
        self.gridLayout.addWidget(self.lineEdit_pesonacer, 5, 2, 1, 1)
        self.lineEdit_pesonacer.setAlignment(QtCore.Qt.AlignCenter)
        
        self.lineEdit_pesoactual = QtWidgets.QLineEdit(self.frame_escribir)
        self.lineEdit_pesoactual.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_pesoactual.setObjectName("lineEdit_pesoactual")
        self.gridLayout.addWidget(self.lineEdit_pesoactual, 6, 2, 1, 1)
        self.lineEdit_pesoactual.setAlignment(QtCore.Qt.AlignCenter)
        
        self.lineEdit_fechaingreso = QtWidgets.QLineEdit(self.frame_escribir)
        self.lineEdit_fechaingreso.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_fechaingreso.setObjectName("lineEdit_fechaingreso")
        self.gridLayout.addWidget(self.lineEdit_fechaingreso, 7, 2, 1, 1)
        self.lineEdit_fechaingreso.setAlignment(QtCore.Qt.AlignCenter)
    
        self.lineEdit_idmedico = QtWidgets.QLineEdit(self.frame_escribir)
        self.lineEdit_idmedico.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_idmedico.setObjectName("lineEdit_idmedico")
        self.lineEdit_idmedico.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.lineEdit_idmedico, 8, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_escribir)
        self.verticalLayout.addWidget(self.frame_arriba)
        
        self.frame_botones = QtWidgets.QFrame(self.centralwidget)
        self.frame_botones.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botones.setObjectName("frame_botones")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_botones)
        self.horizontalLayout.setContentsMargins(2, 4, 2, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.boton_guardar = QtWidgets.QPushButton(self.frame_botones)
        self.boton_guardar.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.boton_guardar.setFont(font)
        self.boton_guardar.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.boton_guardar.setObjectName("boton_guardar")
        self.horizontalLayout.addWidget(self.boton_guardar)
        self.verticalLayout.addWidget(self.frame_botones)
        
        self.boton_historial = QtWidgets.QPushButton(self.frame_botones)
        self.boton_historial.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.boton_historial.setFont(font)
        self.boton_historial.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.boton_historial.setObjectName("boton_historial")
        self.horizontalLayout.addWidget(self.boton_historial)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        #self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "  Ingresar datos del paciente"))
        self.label_titulo.setText(_translate("MainWindow", "Datos del paciente"))
        self.label_8.setText(_translate("MainWindow", "Fecha de ingreso (DD.MM.AAAA):"))
        self.label_7.setText(_translate("MainWindow", "Peso actual [g]:"))
        self.label_3.setText(_translate("MainWindow", "Apellido:"))
        self.label_4.setText(_translate("MainWindow", "Fecha de nacimiento (DD.MM.AAAA):"))
        self.label_9.setText(_translate("MainWindow", "Médico:"))
        #self.label_5.setText(_translate("MainWindow", "Edad [días]:"))
        self.label_2.setText(_translate("MainWindow", "Nombre:"))
        self.label_6.setText(_translate("MainWindow", "Peso al nacer [g]:"))
        self.boton_historial.setText(_translate("MainWindow", "Historial"))
        self.boton_guardar.setText(_translate("MainWindow", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = RegistrarDatosPaciente()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
